use_frameworks!

target 'CPLKeyboardManager_Example' do
  pod 'CPLKeyboardManager', :path => '../'

  target 'CPLKeyboardManager_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.1.0'
    pod 'Nimble', '~> 6.1.0'
  end
end
